const quotes=[
    { quote: "Don't judge a book by its cover.",
      translate: "겉모습만 보고 판단하지 마라.",
    },
    { quote: "No sweat, No sweet.",
      translate: "땀 없인 달콤함도 얻을 수 없다.",
    },
    { quote: "He can do, she can do, why not me?",
      translate: "그도 하고 그녀도 하는데 내가 안되겠어?",
    },
    { quote: "If not now, then when?",
      translate: "지금이 아니라면, 언제 할 것인가?",
    },
    { quote: "Time is gold.",
      translate: "시간은 금이다.",
    },
    { quote: "This too shall pass away.",
      translate: "이 또한 지나가리라.",
    },
    { quote: "Love what you do.",
      translate: "네가 하는 일을 사랑하라.",
    },
    { quote: "Life is unfair, get used to it.",
      translate: "인생은 불공평하다, 익숙해져라.",
    },
    { quote: "Live live there is no tomorrow.",
      translate: "내일이 없는 것처럼 살아라.",
    },
    { quote: "Don't waste your youth.",
      translate: "당신의 젊음을 낭비하지 마라.",
    },
    { quote: "Life is all about timing.",
      translate: "인생은 타이밍이다.",
    },
    { quote: "Despite the forecast, live like it's spring.",
      translate: "일기예보에도 불구하고, 봄처럼 살아가라.",
    },
    { quote: "Be gentle first with yourself.",
      translate: "먼저 자기 자신에게 온화해져라.",
    },
    { quote: "All we have is now.",
      translate: "우리가 가진 것은 지금 뿐이다.",
    },
    { quote: "Believe in yourself.",
      translate: "너 자신을 믿어라.",
    },
    { quote: "No great man ever complains of want of opportunity.",
      translate: "훌륭한 사람은 기회가 없음을 불평하지 않는다.",
    },
    { quote: "Love what you have.",
      translate: "네가 가진 것을 사랑하라.",
    },
    { quote: "It ain't over till it's over.",
      translate: "끝날 때까지 끝난 게 아니다.",
    },
    ];
    const qoute = document.querySelector("#quotes span:first-child");
    
    const translate = document.querySelector("#quotes span:last-child");
    
    const todaysQuote = (quotes[Math.floor(Math.random()*quotes.length)]);
    
    qoute.innerText = todaysQuote.quote;
    translate.innerText = todaysQuote.translate;
